language: node_js
node_js:
  - 8

sudo: false

#before_script:
#  - npm install -g grunt-cli

install:
  - npm install

script:
  - npm run test

branches:
  only:
    - master
#after_success:
#    - npm run coveralls

#after_success:
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
