/// <reference path="typings/index.d.ts" />
export var root = carmi.root
export var compile = carmi.compile
export var arg0 = carmi.arg0
export var arg1 = carmi.arg1
export var arg2 = carmi.arg2
export var setter = carmi.setter
export var splice = carmi.splice
export var chain = carmi.chain
export var and = carmi.and
export var or = carmi.or
